languageCode = "en-us"
title = "Cocoon Rwanda"
baseURL = "http://localhost:1313/"
theme = "dopetrope"

[params.portfolio]
    title = "Appartments"
    foldername = "appartments"
    findoutmoretext = "Find out more"

[params.blog]
    title = "Houses"
    viewalltext = "View All"
    foldername = "houses"

[params.settings]
    googleanalytics = "UA-XXXXXXXXX-X"
